
--- Script de Criação de Tabelas ---

-- MySQL Script generated by MySQL Workbench
-- dom 11 abr 2021 13:02:52 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb --
DROP SCHEMA IF EXISTS `MinasValley`;
CREATE SCHEMA IF NOT EXISTS `MinasValley` DEFAULT CHARACTER SET utf8;
USE `MinasValley`;
-- -----------------------------------------------------

-- ----------CREATE TABLES------------------------------

-- -----------------------------------------------------
-- Table `Cadastro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cadastro` ;

CREATE TABLE IF NOT EXISTS `Cadastro` (
  `NomeUsuario` VARCHAR(80) NOT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(15) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `Id` CHAR(8) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(15) NOT NULL,
  `IdCadastro` VARCHAR(80) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projeto` ;

CREATE TABLE IF NOT EXISTS `Projeto` (
  `Id` CHAR(8) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(80) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  `IdUsuario` CHAR(8) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Startup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Startup` ;

CREATE TABLE IF NOT EXISTS `Startup` (
  `Id` CHAR(8) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(80) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  `IdUsuario` CHAR(8) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

