
--- Script de Criação de Restrições ---

-- MySQL Script generated by MySQL Workbench
-- dom 11 abr 2021 13:02:52 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

USE `MinasValley`;

-- ----------ALTER TABLES------------------------------

-- -----------------------------------------------------
-- Table `Cadastro`
-- -----------------------------------------------------
	ALTER TABLE `Cadastro` ADD CONSTRAINT `PK_Cadastro` PRIMARY KEY (`NomeUsuario`);
	  ON DELETE SET NULL
    ON UPDATE CASCADE;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
	ALTER TABLE `Usuario` ADD CONSTRAINT `PK_Usuario` PRIMARY KEY (`Id`);
	ALTER TABLE `Usuario` ADD CONSTRAINT `FK_Usuario_Cadastro`
    FOREIGN KEY (`IdCadastro`)
    REFERENCES `Cadastro` (`NomeUsuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE;


-- -----------------------------------------------------
-- Table `Projeto`
-- -----------------------------------------------------
	ALTER TABLE `Projeto` ADD CONSTRAINT `PK_Projeto` PRIMARY KEY (`Id`, `IdUsuario`);
	ALTER TABLE `Projeto` ADD CONSTRAINT `FK_Projeto_Usuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `Usuario` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE;


-- -----------------------------------------------------
-- Table `Startup`
-- -----------------------------------------------------
	ALTER TABLE `Startup` ADD CONSTRAINT `PK_Startup` PRIMARY KEY (`Id`, `IdUsuario`);
	ALTER TABLE `Startup` ADD CONSTRAINT `FK_Startup_Usuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `Usuario` (`Id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE;
